from flask import Flask, render_template_string, jsonify, request, session, redirect, url_for
import sqlite3
import os
import json
import functools
import uuid
import threading
import asyncio
import hmac
import hashlib
import base64
from datetime import datetime, timedelta

# --- IMPORT FETCHER ---
# This starts the background prediction bot
import fetcher

app = Flask(__name__)

# --- CONFIGURATION ---
# CHANGE THIS TO A RANDOM SECRET STRING FOR SECURITY
app.secret_key = "TITAN_SECURE_KEY_CHANGE_THIS" 
ADMIN_PASSWORD = "admin" 

# --- CRITICAL: MUST MATCH YOUR LOCAL GENERATOR ---
OFFLINE_SECRET = "TITAN_OFFLINE_SECRET_CODE_123"

# --- RENDER PERSISTENT STORAGE SETUP ---
# Detects if running on Render or Local PC to set correct DB path
if os.path.exists('/var/lib/data'):
    BASE_DIR = '/var/lib/data'
elif os.path.exists('/data'):
    BASE_DIR = '/data'
else:
    BASE_DIR = os.path.abspath(os.path.dirname(__file__))

DB_PATH = os.path.join(BASE_DIR, 'titan_db.sqlite')
DASHBOARD_FILE = os.path.join(BASE_DIR, 'dashboard_data.json')

print(f"[SYSTEM] Database Path: {DB_PATH}")

def create_connection():
    """Creates a connection to the SQLite database."""
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn

def ensure_tables():
    """Sets up the database tables if they don't exist."""
    conn = create_connection()
    
    # 1. ACCESS KEYS TABLE
    # Stores keys, expiration, and the LOCKED DEVICE ID
    conn.execute('''CREATE TABLE IF NOT EXISTS access_keys (
                    key_code TEXT PRIMARY KEY,
                    note TEXT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    expires_at TIMESTAMP,
                    bound_device_id TEXT,
                    is_active INTEGER DEFAULT 1
                )''')
    
    # 2. ACTIVE SESSIONS TABLE
    # Tracks who is currently online
    conn.execute('''CREATE TABLE IF NOT EXISTS active_sessions (
                    session_id TEXT PRIMARY KEY,
                    key_code TEXT,
                    ip_address TEXT,
                    last_heartbeat TIMESTAMP
                )''')
    
    conn.commit()
    conn.close()

# Run Setup
ensure_tables()

# --- HELPER: VALIDATE OFFLINE KEY ---
def validate_offline_key(key_string):
    """
    Validates a key generated by your local PC generator.
    Returns: (True/False, DataDict or ErrorMessage)
    """
    if not key_string.startswith("TITAN-"):
        return False, "Invalid Key Format"
    
    try:
        parts = key_string.split('-')
        if len(parts) != 3: return False, "Corrupt Key Structure"
        
        payload_b64 = parts[1]
        signature = parts[2]
        
        # 1. Fix Base64 Padding and Decode
        padding = len(payload_b64) % 4
        if padding: payload_b64 += '=' * (4 - padding)
        payload_raw = base64.urlsafe_b64decode(payload_b64).decode()
        
        # 2. Verify Signature (HMAC)
        # We must re-calculate the signature using the SECRET and compare it
        calc_sig = hmac.new(OFFLINE_SECRET.encode(), payload_raw.encode(), hashlib.sha256).hexdigest()[:8].upper()
        
        if signature != calc_sig:
            return False, "Fake Key (Signature Mismatch)"
            
        # 3. Extract Data: timestamp|max_devices|name
        ts, max_dev, name = payload_raw.split('|')
        
        # 4. Check Expiration
        expire_dt = datetime.fromtimestamp(int(ts))
        if datetime.now() > expire_dt:
            return False, "Key has Expired"
            
        return True, {
            "name": name,
            "expires": expire_dt,
            "max_devices": int(max_dev)
        }
    except Exception as e:
        return False, f"Key Validation Error: {e}"

# --- BACKGROUND WORKER ---
def start_fetcher_loop():
    """Runs the fetcher in a background thread."""
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    try: 
        loop.run_until_complete(fetcher.main_loop())
    except Exception as e: 
        print(f"Fetcher Error: {e}")

# Only start the background thread if this is the main process
if os.environ.get("WERKZEUG_RUN_MAIN") != "true":
    t = threading.Thread(target=start_fetcher_loop, daemon=True)
    t.start()

# --- AUTHENTICATION HELPERS ---
def cleanup_sessions():
    """Removes sessions that have been inactive for >60 seconds."""
    conn = create_connection()
    limit = datetime.now() - timedelta(seconds=60)
    conn.execute("DELETE FROM active_sessions WHERE last_heartbeat < ?", (limit,))
    conn.commit()
    conn.close()

def login_required(f):
    @functools.wraps(f)
    def wrapped(*args, **kwargs):
        if not session.get('authenticated'):
            return redirect(url_for('login'))
        return f(*args, **kwargs)
    return wrapped

def admin_required(f):
    @functools.wraps(f)
    def wrapped(*args, **kwargs):
        if not session.get('is_admin'):
            return redirect(url_for('admin_login'))
        return f(*args, **kwargs)
    return wrapped

# --- ROUTES ---

@app.route('/login', methods=['GET', 'POST'])
def login():
    error = None
    if request.method == 'POST':
        key_input = request.form.get('key', '').strip()
        device_fingerprint = request.form.get('device_id', '').strip() # From JS
        
        cleanup_sessions()
        
        conn = create_connection()
        # 1. Check if key is already in DB (Known Key)
        db_key = conn.execute("SELECT * FROM access_keys WHERE key_code = ?", (key_input,)).fetchone()
        
        key_info = None
        
        if db_key:
            # --- SCENARIO A: EXISTING KEY ---
            if db_key['is_active'] == 0:
                error = "ACCESS DENIED: KEY IS BANNED"
            elif datetime.now() > datetime.strptime(db_key['expires_at'], '%Y-%m-%d %H:%M:%S'):
                error = "ACCESS DENIED: KEY EXPIRED"
            else:
                # DEVICE LOCK CHECK
                if db_key['bound_device_id'] and db_key['bound_device_id'] != device_fingerprint:
                    error = "ACCESS DENIED: LOCKED TO ANOTHER DEVICE"
                else:
                    # Valid!
                    key_info = {"key": key_input}
                    # Self-Healing: If ID was null (from a reset), bind it now
                    if not db_key['bound_device_id']:
                         conn.execute("UPDATE access_keys SET bound_device_id = ? WHERE key_code = ?", (device_fingerprint, key_input))
                         conn.commit()
        else:
            # --- SCENARIO B: NEW/OFFLINE KEY ---
            is_valid, data = validate_offline_key(key_input)
            if is_valid:
                # First time use: Save it to DB and Bind Device
                try:
                    conn.execute("INSERT INTO access_keys (key_code, note, expires_at, bound_device_id) VALUES (?, ?, ?, ?)",
                                 (key_input, data['name'], data['expires'].strftime('%Y-%m-%d %H:%M:%S'), device_fingerprint))
                    conn.commit()
                    key_info = {"key": key_input}
                except Exception as e:
                    error = "Database Error: Could not register key"
            else:
                error = data # Error message from validator

        conn.close()
        
        if key_info and not error:
            # SUCCESS
            session['authenticated'] = True
            session['user_key'] = key_input
            session['session_uuid'] = str(uuid.uuid4())
            return redirect(url_for('index'))

    # LOGIN PAGE HTML
    return f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
            body {{ background-color: #050505; color: #00ff41; font-family: monospace; display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100vh; margin: 0; }}
            input {{ background: #111; border: 1px solid #333; color: white; padding: 12px; width: 280px; text-align: center; margin-bottom: 20px; font-size: 16px; outline: none; }}
            button {{ background: #00ff41; color: black; border: none; padding: 12px 30px; font-weight: bold; font-size: 16px; cursor: pointer; }}
            .error {{ color: #ff0055; margin-bottom: 20px; font-weight: bold; text-align: center; }}
            h1 {{ margin-bottom: 5px; letter-spacing: 2px; }}
        </style>
    </head>
    <body>
        <h1>TITAN V700</h1>
        <div style="color:#444; font-size:10px; margin-bottom:30px;">SECURE ACCESS GATEWAY</div>
        
        <div class="error">{error if error else ''}</div>
        
        <form method="post">
            <input type="hidden" name="device_id" id="did">
            <input type="text" name="key" placeholder="ENTER LICENSE KEY" autocomplete="off">
            <br>
            <button>AUTHENTICATE</button>
        </form>
        
        <script>
            // DEVICE FINGERPRINT SCRIPT
            // Generates a permanent ID for this browser/phone
            let d = localStorage.getItem('titan_device_id');
            if(!d) {{ 
                d = 'DEV-' + Math.random().toString(36).substr(2,9).toUpperCase() + '-' + Date.now(); 
                localStorage.setItem('titan_device_id', d); 
            }}
            document.getElementById('did').value = d;
        </script>
    </body>
    </html>
    """

@app.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('login'))

@app.route('/heartbeat', methods=['POST'])
def heartbeat():
    return jsonify({"status": "ok"})

@app.route('/data')
def data():
    """Serves the dashboard JSON data."""
    if not session.get('authenticated'): 
        return jsonify({"status": "reload"})
    
    try:
        if os.path.exists(DASHBOARD_FILE):
            with open(DASHBOARD_FILE, 'r') as f: return jsonify(json.load(f))
    except: pass
    return jsonify({"prediction": "LOADING...", "status_text": "WAITING FOR DATA..."})

# --- ADMIN PANEL ---

@app.route('/admin_login', methods=['GET', 'POST'])
def admin_login():
    if request.method == 'POST':
        if request.form.get('password') == ADMIN_PASSWORD:
            session['is_admin'] = True
            return redirect(url_for('admin_panel'))
    return '<body style="background:#111; color:white; display:flex; justify-content:center; align-items:center; height:100vh;"><form method="post"><input type="password" name="password" placeholder="Admin Password" style="padding:10px;"><button>Login</button></form></body>'

@app.route('/admin', methods=['GET', 'POST'])
@admin_required
def admin_panel():
    cleanup_sessions()
    conn = create_connection()
    msg = ""

    # ACTION: RESET DEVICE LOCK
    if request.method == 'POST' and 'reset_key' in request.form:
        target = request.form.get('reset_key')
        conn.execute("UPDATE access_keys SET bound_device_id = NULL WHERE key_code = ?", (target,))
        conn.commit()
        msg = f"Reset Device Lock for {target}"

    # ACTION: DELETE KEY
    if request.method == 'POST' and 'delete_key' in request.form:
        target = request.form.get('delete_key')
        conn.execute("DELETE FROM access_keys WHERE key_code = ?", (target,))
        conn.commit()
        msg = f"Deleted Key {target}"

    # FETCH DATA
    keys = conn.execute("SELECT * FROM access_keys ORDER BY created_at DESC").fetchall()
    conn.close()
    
    rows = ""
    for k in keys:
        # Determine status
        if k['bound_device_id']:
            dev_status = f"<span style='color:orange'>🔒 LOCKED</span> <span style='font-size:10px'>({k['bound_device_id'][:8]}...)</span>"
        else:
            dev_status = "<span style='color:#00ff41'>🔓 OPEN</span>"
            
        rows += f"""
        <tr style="border-bottom:1px solid #ddd;">
            <td style="padding:10px; font-family:monospace;"><strong>{k['key_code']}</strong></td>
            <td>{k['note']}</td>
            <td>{dev_status}</td>
            <td style="font-size:12px;">{k['expires_at']}</td>
            <td>
                <form method="POST" style="display:inline" onsubmit="return confirm('Unlock this key for a new device?');">
                    <input type="hidden" name="reset_key" value="{k['key_code']}">
                    <button style="cursor:pointer; font-size:10px; padding:5px;">RESET ID</button>
                </form>
                <form method="POST" style="display:inline" onsubmit="return confirm('Delete this key permanently?');">
                    <input type="hidden" name="delete_key" value="{k['key_code']}">
                    <button style="color:white; background:red; border:none; cursor:pointer; font-size:10px; padding:5px;">DEL</button>
                </form>
            </td>
        </tr>"""

    return f"""
    <!DOCTYPE html>
    <html>
    <head><title>Titan Admin</title></head>
    <body style="font-family:sans-serif; background:#f4f4f4; padding:20px;">
        <div style="max-width:1100px; margin:0 auto;">
            <h1>TITAN V700 MANAGER</h1>
            <p style="color:blue; font-weight:bold;">{msg}</p>
            <div style="background:white; padding:20px; box-shadow:0 2px 5px rgba(0,0,0,0.1);">
                <h3>Registered Keys (Offline & Online)</h3>
                <table style="width:100%; border-collapse:collapse;">
                    <thead style="background:#222; color:white;">
                        <tr>
                            <th style="padding:10px; text-align:left;">Key Code</th>
                            <th style="text-align:left;">User Name</th>
                            <th style="text-align:left;">Device Status</th>
                            <th style="text-align:left;">Expires</th>
                            <th style="text-align:left;">Actions</th>
                        </tr>
                    </thead>
                    <tbody>{rows}</tbody>
                </table>
            </div>
            <br>
            <a href="/">Go to Dashboard</a> | <a href="/logout">Logout</a>
        </div>
    </body>
    </html>
    """

@app.route('/')
@login_required
def index():
    return render_template_string(HTML_TEMPLATE)

# --- CLIENT DASHBOARD HTML (WITH HISTORY LIST) ---
HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>TITAN V700 LIVE</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;800&display=swap');
        body { background-color: #050505; color: #fff; font-family: 'JetBrains Mono', monospace; margin: 0; padding: 10px; display: flex; flex-direction: column; align-items: center; min-height: 100vh; }
        
        .card { width: 100%; max-width: 400px; background: #111; border: 1px solid #222; border-radius: 12px; padding: 20px; text-align: center; margin-bottom: 20px; box-shadow: 0 0 20px rgba(0,0,0,0.5); }
        
        .header { display: flex; justify-content: space-between; width: 100%; max-width: 400px; margin-bottom: 20px; border-bottom: 1px solid #222; padding-bottom: 10px; }
        .logo { font-weight: 800; font-size: 18px; }
        .accent { color: #00ff41; }
        
        .period { color: #666; font-size: 14px; margin-top: 10px; }
        .prediction { font-size: 56px; font-weight: 800; margin: 15px 0; line-height: 1; }
        .big { color: #00ff41; text-shadow: 0 0 30px rgba(0,255,65,0.3); }
        .small { color: #ff0055; text-shadow: 0 0 30px rgba(255,0,85,0.3); }
        .wait { color: #444; }
        
        .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin-top: 20px; }
        .info-box { background: #1a1a1a; padding: 10px; border-radius: 6px; font-size: 12px; }
        .info-label { color: #666; font-size: 10px; display: block; margin-bottom: 4px; }
        
        /* HISTORY LIST STYLES */
        .history-card { width: 100%; max-width: 400px; background: #111; border: 1px solid #222; border-radius: 12px; overflow: hidden; }
        .history-header { background: #1a1a1a; padding: 10px; font-size: 12px; color: #888; border-bottom: 1px solid #222; text-align: center; font-weight: bold; letter-spacing: 1px; }
        .history-list { max-height: 300px; overflow-y: auto; padding: 0; margin: 0; }
        .history-item { display: flex; justify-content: space-between; padding: 10px 15px; border-bottom: 1px solid #1a1a1a; font-size: 12px; }
        .h-win { color: #00ff41; font-weight: bold; } 
        .h-loss { color: #ff0055; font-weight: bold; }
        .h-pending { color: #888; }
        
        /* SCROLLBAR */
        ::-webkit-scrollbar { width: 6px; }
        ::-webkit-scrollbar-track { background: #111; }
        ::-webkit-scrollbar-thumb { background: #333; border-radius: 3px; }
    </style>
</head>
<body>
    <div class="header">
        <div class="logo">TITAN <span class="accent">V700</span></div>
        <a href="/logout" style="color:#666; text-decoration:none; font-size:12px;">LOGOUT</a>
    </div>

    <div class="card">
        <div class="period" id="period">WAITING...</div>
        
        <div id="prediction" class="prediction wait">---</div>
        
        <div style="color:#888; font-size:12px;" id="status">CONNECTING...</div>

        <div class="info-grid">
            <div class="info-box">
                <span class="info-label">CONFIDENCE</span>
                <span id="conf" style="font-weight:bold; color:white;">0%</span>
            </div>
            <div class="info-box">
                <span class="info-label">STRATEGY</span>
                <span id="strat" style="font-weight:bold; color:white;">---</span>
            </div>
        </div>
        
        <div style="margin-top:15px; font-size:12px; color:#ccc;">
            WINS: <span id="wins" style="color:#00ff41; font-weight:bold">0</span> | LOSS: <span id="losses" style="color:#ff0055; font-weight:bold">0</span>
        </div>
    </div>

    <div class="history-card">
        <div class="history-header">RECENT OUTCOMES</div>
        <div id="history-box" class="history-list">
            <div style="padding:20px; text-align:center; color:#444;">No history data available yet...</div>
        </div>
    </div>

    <script>
        // HEARTBEAT to keep session alive
        setInterval(() => { fetch('/heartbeat', {method: 'POST'}); }, 5000);

        function update() {
            fetch('/data').then(r => r.json()).then(d => {
                if(d.status === 'reload') location.reload();

                // 1. UPDATE MAIN DISPLAY
                document.getElementById('period').innerText = "PERIOD " + d.period;
                
                const p = document.getElementById('prediction');
                p.innerText = d.prediction;
                // Reset classes then add the right one
                p.className = 'prediction ' + (d.prediction === 'BIG' ? 'big' : (d.prediction === 'SMALL' ? 'small' : 'wait'));
                
                document.getElementById('status').innerText = d.status_text;
                document.getElementById('conf').innerText = d.confidence || "0%";
                document.getElementById('strat').innerText = d.strategy || "---";
                
                // 2. UPDATE STATS
                if(d.stats) {
                    document.getElementById('wins').innerText = d.stats.wins;
                    document.getElementById('losses').innerText = d.stats.losses;
                }

                // 3. UPDATE HISTORY LIST
                if (d.history && d.history.length > 0) {
                    let html = "";
                    d.history.forEach(h => {
                        let colorClass = h.result === 'WIN' ? 'h-win' : 'h-loss';
                        html += `<div class="history-item">
                            <span style="color:#666">${h.period}</span>
                            <span style="font-weight:bold">${h.pred}</span>
                            <span class="${colorClass}">${h.result}</span>
                        </div>`;
                    });
                    document.getElementById('history-box').innerHTML = html;
                }
            }).catch(e => console.log(e));
        }
        
        // Poll every second
        setInterval(update, 1000);
    </script>
</body>
</html>
"""

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)
